#!/bin/sh
# Generated by hamroh (agy_worker.config_writer). Do not edit.
name=$(cat | sed -n 's/.*"name"[ ]*:[ ]*"\([^"]*\)".*/\1/p' | head -1)
allow="call_mcp_tool list_resources read_resource"
deny="search_web read_url_content generate_image view_file list_dir write_to_file create_file replace_file_content multi_replace_file_content grep_search codebase_search run_command execute_command define_subagent invoke_subagent manage_subagents"
for t in $deny; do
  [ "$name" = "$t" ] && { echo '{"decision":"deny","reason":"hamroh: tool not permitted"}'; exit 0; }
done
echo '{"decision":"allow"}'
